### PR TITLE
fix: form.getvalue(key) instead of .getlist(key)

### PR DESCRIPTION
**Pull request by aleksei-dolzhenkov**
I think that was a bug, all single values was turning into lists.

### CODE REVIEW

**Comment by yohanboniface** [comment]
Not sure this is needed.
Selecting a single value is then handled by Falcon `get_param`, see https://github.com/falconry/falcon/blob/d43d295c6eecb8fb65014a2b47ffa788b42575b7/falcon/request.py#L923
One may still use `get_param_as_list`, what do you think?

**Comment by aleksei-dolzhenkov** [comment]
`get_param` and `get_param_as_list` will works as before, but now there is correct values in `req.params` dict.

That's will allow us to use it with, for example, marshmallow Schema.
```
class schema(marshmallow.Schema):
    a = fields.Str()

result = schema().load(req.params)
```

**Comment by yohanboniface** [comment]
humm, but what if you pass multiple values as file attribute?

**Comment by aleksei-dolzhenkov** [comment]
well, multiple file in one fields does not work properly right now anyway.
but, in order to fix it, i would rewrite `process_request` to something like that:
```
    def process_request(self, req, resp, **kwargs):

        if 'multipart/form-data' not in (req.content_type or ''):
            return

        # This must be done to avoid a bug in cgi.FieldStorage.
        req.env.setdefault('QUERY_STRING', '')

        form = self.parse(stream=req.stream, environ=req.env)

        def field_value(value):
            if type(value) is type([]):
                return map(field_value, value)

            if not getattr(value, 'filename', False):
                return value.value

            return value

        for key in form:
            # TODO: put files in req.files instead when #493 get merged.
            req._params[key] = field_value(form[key])

```

**Comment by yohanboniface** [comment]
This (scary) PR should make you happy: #10 ;)

**Comment by aleksei-dolzhenkov** [comment]
@yohanboniface yes, it makes ^^

**Pull request closed without merging**
